// Câu hỏi biên soạn lại theo kỹ năng trong đề 6101 và 6102; xem CONTENT_REVIEW.md.
const bank=[];
function mc(id,topic,prompt,options,answer,explanation,source,hint,graph){bank.push({id,topic,type:'choice',prompt,options,answer,explanation,source,hint,graph});}
function num(id,topic,prompt,answer,unit,explanation,source,hint,graph,tolerance=.001){bank.push({id,topic,type:'number',prompt,answer,unit,explanation,source,hint,graph,tolerance});}
function tf(id,topic,prompt,answer,explanation,source,hint,graph){mc(id,topic,prompt,['Đúng','Sai'],answer?0:1,explanation,source,hint,graph);bank.at(-1).type='boolean';}
mc('b01','basics','Số dao động toàn phần thực hiện trong một giây được gọi là gì?',['Chu kì','Tần số','Pha ban đầu','Biên độ'],1,'Tần số f là số dao động toàn phần trong một đơn vị thời gian. Đơn vị là Hz; f = 1/T.','6101 · I.1','Phân biệt số lần trong một giây với thời gian của một lần.');
mc('b02','basics','Vật dao động theo x = 3cos(4πt) (cm). Biên độ bằng bao nhiêu?',['3 cm','6 cm','4π cm','12 cm'],0,'Biên độ là hệ số dương trước hàm cos: A = 3 cm. Độ dài quỹ đạo là 2A = 6 cm.','6101 · I.2 (bổ sung ω)','Đối chiếu với x = Acos(ωt + φ).');
mc('b03','basics','Chu kì là khoảng thời gian ngắn nhất để vật…',['Trở lại vị trí ban đầu bất kể chiều chuyển động','Đi từ biên âm đến biên dương','Trở lại trạng thái dao động ban đầu','Đi từ cân bằng đến biên'],2,'Trạng thái gồm vị trí và chiều chuyển động. Cùng một vị trí có thể được đi qua hai lần trong một chu kì với chiều khác nhau.','6102 · I.3','Trạng thái không chỉ là vị trí.');
mc('b04','basics','Với x = 5cos(ωt + π/2) (cm), pha ban đầu là…',['ωt','π/2 rad','5 rad','ωt + π/2'],1,'Pha ban đầu φ = π/2 rad; pha tại thời điểm t là ωt + π/2.','6101 · I.7','Pha ban đầu là pha khi t = 0.');
mc('b05','basics','Li độ, vận tốc và gia tốc trong cùng một dao động điều hoà có cùng…',['Biên độ','Pha ban đầu','Tần số góc','Giá trị cực đại'],2,'Cả ba biến thiên điều hoà với cùng ω, nên cùng chu kì và tần số. Biên độ và pha nói chung khác nhau.','6101 · I.8','Xét hệ số của t trong các biểu thức.');
mc('b06','basics','Hai dao động x₁ = 10cos(100πt − π/2) và x₂ = 10cos(100πt + π/2) có độ lệch pha bằng…',['0','π/4 rad','π/2 rad','π rad'],3,'|Δφ| = |π/2 − (−π/2)| = π rad. Hai dao động ngược pha.','6101 · I.12','Lấy hiệu hai pha ban đầu.');
mc('b07','basics','Vật dao động điều hoà có biên độ A. Độ dài quỹ đạo là…',['A/2','A','2A','4A'],2,'Vật chuyển động trên đoạn từ −A đến +A nên độ dài quỹ đạo là 2A. Trong một chu kì, quãng đường đi được là 4A.','6102 · I.7','Độ dài đoạn chuyển động khác quãng đường đi trong một chu kì.');
mc('b08','basics','Tốc độ của vật dao động điều hoà lớn nhất ở đâu?',['Biên dương','Biên âm','Vị trí cân bằng','Mọi vị trí như nhau'],2,'Tại x = 0, động năng cực đại và tốc độ đạt vmax = ωA. Ở hai biên, tốc độ bằng 0.','6102 · I.6','Ở đâu động năng lớn nhất?');
mc('b09','basics','Gia tốc a = −ω²x. Giá trị nhỏ nhất của gia tốc là…',['0','−ω²A','ω²A','−ωA'],1,'Giá trị nhỏ nhất là amin = −ω²A tại x = +A. Độ lớn gia tốc cực đại là ω²A.','6101 · I.10; 6102 · I.9','Phân biệt giá trị nhỏ nhất với độ lớn nhỏ nhất.');
num('b10','basics','Vật dao động trên quỹ đạo dài 8 cm, chu kì 2 s. Quãng đường đi trong 2 s bằng bao nhiêu?',16,'cm','2A = 8 cm ⇒ A = 4 cm. Trong đúng một chu kì, vật đi 4A = 16 cm, không phụ thuộc vị trí xuất phát.','6101 · III.2','2 s là một chu kì; quỹ đạo dài 2A.');
num('b11','basics','Vật dao động trên quỹ đạo dài 4 cm, chu kì 1 s. Quãng đường đi trong 1 s bằng bao nhiêu?',8,'cm','A = 4/2 = 2 cm. Trong một chu kì: s = 4A = 8 cm.','6102 · III.2','Quãng đường trong một chu kì bằng hai lần độ dài quỹ đạo.');
num('b12','basics','Dao động có tần số 2 Hz. Chu kì bằng bao nhiêu?',.5,'s','T = 1/f = 1/2 = 0,5 s.','Biến thể kỹ năng chu kì–tần số','Dùng T = 1/f.');
tf('b13','basics','Robot nói: “Khi vật ở biên, vận tốc và gia tốc đều bằng 0.”',false,'Ở biên, vận tốc bằng 0 nhưng |a| = ω²A lớn nhất. Gia tốc chỉ bằng 0 khi vật qua vị trí cân bằng.','Biến thể 6101 · I.10–11','Hãy dùng a = −ω²x tại x = ±A.');
mc('b14','basics','Vật đang ở phía dương và đi ra biên dương. Chọn mô tả đúng.',['v > 0, a > 0; nhanh dần','v > 0, a < 0; chậm dần','v < 0, a > 0; chậm dần','v < 0, a < 0; nhanh dần'],1,'Vật đi theo chiều dương nên v > 0. Vì x > 0 nên a < 0. Vận tốc và gia tốc ngược chiều, tốc độ giảm.','Bổ trợ kỹ năng x, v, a','Gia tốc luôn hướng về vị trí cân bằng.');
num('b15','basics','Vật có A = 4 cm và ω = 5 rad/s. Tốc độ cực đại bằng bao nhiêu?',20,'cm/s','vmax = ωA = 5 × 4 = 20 cm/s. A dùng cm nên kết quả là cm/s.','Biến thể 6102 · I.1','vmax = ωA.');
mc('b16','basics','Hai phương trình đều có pha 100πt + π/2. Hai dao động này…',['Cùng pha','Ngược pha','Vuông pha','Không xác định được'],0,'Hai pha bằng nhau tại mọi thời điểm nên độ lệch pha bằng 0.','6102 · I.2','So sánh trực tiếp hai pha.');
const gx={kind:'sin',label:'x (cm)',A:10,T:2,phase:Math.PI,max:2.5,step:.5,time:'t (s)'};
const gv={kind:'sin',label:'v (cm/s)',A:40,T:.8,phase:0,max:1.6,step:.4,time:'t (s)'};
const gf={kind:'sin',label:'x (cm)',A:2,T:20,phase:2*Math.PI/3,max:35,step:10,time:'t (ms)'};
num('g01','graphs','Đọc đồ thị: biên độ dao động bằng bao nhiêu?',10,'cm','Li độ lớn nhất là +10 cm, nhỏ nhất là −10 cm. Biên độ A = 10 cm, không phải 20 cm.','6101 · II.1a; 6102 · II.1b','Biên độ là độ lệch lớn nhất so với vị trí cân bằng.',gx);
num('g02','graphs','Đọc đồ thị: chu kì dao động bằng bao nhiêu?',2,'s','Vật ở biên âm tại t = 0 và lại ở biên âm tại t = 2 s. Vì vậy T = 2 s.','6102 · II.1d','Tìm hai điểm liên tiếp có cùng vị trí và cùng chiều chuyển động.',gx);
tf('g03','graphs','Theo đồ thị, tại t = 1 s vật đang ở biên dương.',true,'Tại t = 1 s, x = +10 cm = +A nên vật ở biên dương.','6101 · II.1b','Dóng từ t = 1 s lên đường cong.',gx);
tf('g04','graphs','Theo đồ thị, tần số dao động là 2 Hz.',false,'Đồ thị cho T = 2 s nên f = 1/T = 0,5 Hz. Không lấy chu kì làm tần số.','6101 · II.1c','Đọc T trước, sau đó lấy nghịch đảo.',gx);
mc('g05','graphs','Tại t = 1,5 s, vật đang ở đâu và đi theo chiều nào?',['Ở cân bằng, theo chiều dương','Ở cân bằng, theo chiều âm','Ở biên dương','Ở biên âm'],1,'Đồ thị đi qua x = 0 và đang đi xuống tại 1,5 s. Vì vậy v < 0: vật qua cân bằng theo chiều âm.','Biến thể 6101 · II.1d','Chiều vận tốc là dấu độ dốc của đồ thị x–t.',gx);
num('g06','graphs','Từ đồ thị vận tốc, hãy xác định chu kì.',.8,'s','Từ cực đại tại t = 0 đến cực tiểu tại t = 0,4 s là nửa chu kì. T = 0,8 s.','6102 · III.1','Khoảng từ cực đại đến cực tiểu là T/2.',gv);
num('g07','graphs','Từ đồ thị vận tốc, hãy xác định tần số.',1.25,'Hz','T = 0,8 s ⇒ f = 1/0,8 = 1,25 Hz.','6101 · III.1','Đọc chu kì từ hai đỉnh liên tiếp.',gv);
num('g08','graphs','Đồ thị có trục thời gian tính bằng ms. Tốc độ cực đại bằng bao nhiêu cm/s? Làm tròn đến hàng đơn vị.',628,'cm/s','A = 2 cm; T = 20 ms = 0,020 s. ω = 2π/T = 100π rad/s. vmax = ωA = 200π ≈ 628 cm/s.','6101 · III.3','Đổi ms sang s trước khi tính ω.',gf,.01);
num('g09','graphs','Từ đồ thị, tính độ lớn gia tốc cực đại theo m/s². Làm tròn đến hàng đơn vị.',1974,'m/s²','A = 2 cm = 0,02 m; T = 20 ms = 0,02 s; ω = 100π rad/s. amax = ω²A = 200π² ≈ 1974 m/s².','6102 · III.4','Cần đổi cả cm sang m và ms sang s.',gf,.01);
mc('g10','graphs','Theo đồ thị vận tốc, tại t = 0,4 s vật…',['Đứng yên tại biên','Qua cân bằng theo chiều âm','Qua cân bằng theo chiều dương','Có tốc độ bằng 20 cm/s'],1,'v = −40 cm/s là vận tốc có độ lớn cực đại. Vật qua cân bằng theo chiều âm.','Bổ trợ đọc đồ thị v–t','Dấu của vận tốc cho biết chiều; |v| cực đại tại cân bằng.',gv);
const eodd={kind:'energy',A:4,E:32};const eeven={kind:'energy',A:3,E:120};
mc('e01','energy','Với khối lượng và tần số góc không đổi, cơ năng tỉ lệ thuận với…',['Biên độ A','Bình phương biên độ A²','Li độ x','Chu kì T'],1,'W = ½mω²A². Khi m và ω không đổi, W tỉ lệ thuận với A².','6101 · I.6','Dùng biểu thức cơ năng.');
num('e02','energy','Vật có m = 200 g, ω = 20 rad/s, A = 10 cm. Cơ năng bằng bao nhiêu?',.4,'J','m = 0,2 kg; A = 0,1 m. W = ½ × 0,2 × 20² × 0,1² = 0,4 J.','6101 · III.4','Đổi khối lượng sang kg và biên độ sang m.');
num('e03','energy','Vật có m = 100 g, ω = 20 rad/s, A = 10 cm. Cơ năng bằng bao nhiêu?',.2,'J','W = ½ × 0,1 × 20² × 0,1² = 0,2 J.','6102 · III.3','W = ½mω²A², dùng đơn vị SI.');
num('e04','energy','Đọc đồ thị động năng theo li độ: cơ năng của vật bằng bao nhiêu?',32,'mJ','Tại x = 0, thế năng bằng 0 nên động năng cực đại bằng cơ năng: W = 32 mJ.','6101 · IV.1','Cơ năng bằng động năng cực đại.',eodd);
num('e05','energy','Từ đồ thị động năng theo li độ, hãy xác định biên độ.',4,'cm','Động năng bằng 0 ở hai biên x = ±4 cm, nên A = 4 cm.','Bước giải bổ trợ 6101 · IV','Tìm giao điểm của đường cong với trục x.',eodd);
num('e06','energy','Vật có khối lượng 100 g. Từ đồ thị, tính tần số góc.',20,'rad/s','W = 32 mJ = 0,032 J; A = 4 cm = 0,04 m; m = 0,1 kg. ω = √(2W/(mA²)) = 20 rad/s.','6101 · IV.2','Đọc W và A, đổi SI rồi dùng W = ½mω²A².',eodd);
mc('e07','energy','Theo đồ thị, khi động năng bằng 3 lần thế năng, các li độ của vật là…',['Chỉ x = 2 cm','x = ±2 cm','x = ±2√3 cm','x = ±4 cm'],1,'W = Wđ + Wt = 4Wt ⇒ Wt/W = 1/4 = x²/A². Suy ra x = ±A/2 = ±2 cm.','6101 · IV.3','Viết cơ năng theo thế năng trước.',eodd);
num('e08','energy','Đọc đồ thị: biên độ dao động bằng bao nhiêu?',3,'cm','Động năng bằng 0 tại x = ±3 cm, nên A = 3 cm.','6102 · IV.1','Ở biên, vật có tốc độ bằng 0.',eeven);
num('e09','energy','Khối lượng vật là 100 g. Từ đồ thị, tính chu kì, làm tròn đến hàng phần trăm.',.12,'s','W = 0,120 J; A = 0,03 m; m = 0,1 kg. ω = √(2W/(mA²)) ≈ 51,64 rad/s. T = 2π/ω ≈ 0,1217 s, làm tròn được 0,12 s.','6102 · IV.2 (chuẩn hoá yêu cầu làm tròn)','Tính ω từ cơ năng rồi dùng T = 2π/ω.',eeven,.0001);
mc('e10','energy','Khi động năng bằng thế năng, vật có những li độ nào?',['Chỉ x = 1,5√2 cm','x = ±1,5 cm','x = ±1,5√2 cm','x = ±3 cm'],2,'Wt = W/2 ⇒ x²/A² = 1/2 ⇒ x = ±A/√2 = ±1,5√2 cm. Phải lấy cả hai vị trí đối xứng.','6102 · IV.3 (bổ sung dấu ± còn thiếu trong đáp án)','Thế năng phụ thuộc x² nên có hai li độ đối xứng.',eeven);
tf('e11','energy','Trong dao động điều hoà không ma sát, khi vật đi từ cân bằng ra biên, động năng tăng.',false,'Khi vật đi ra biên, tốc độ giảm nên động năng giảm, thế năng tăng. Tổng cơ năng giữ nguyên.','Bổ trợ chuyển hoá năng lượng','Ở cân bằng tốc độ lớn nhất; ở biên tốc độ bằng 0.');
mc('e12','energy','Với x = Acos(ωt + φ), thế năng tính từ vị trí cân bằng có biểu thức nào?',['½mω²A²sin²(ωt + φ)','½mω²A²cos²(ωt + φ)','½mωA²cos(ωt + φ)','½mω²A²'],1,'Wt = ½mω²x² = ½mω²A²cos²(ωt + φ). Biểu thức không phụ thuộc t là cơ năng.','6101 · I.9; 6102 · I.11 (biên soạn lại)','Thay x vào Wt = ½mω²x².');
mc('e13','energy','Với x = Acos(ωt + φ), động năng của vật là…',['½mω²A²sin²(ωt + φ)','½mω²A²cos²(ωt + φ)','½mω²A²sin(ωt + φ)','½mω²A²'],0,'v = −ωA sin(ωt + φ). Wđ = ½mv² = ½mω²A²sin²(ωt + φ).','6101 · I.5; 6102 · I.5 (biên soạn lại)','Bình phương biểu thức vận tốc.');
num('e14','energy','Một vật có cơ năng 0,4 J. Khi thế năng là 0,1 J, động năng bằng bao nhiêu?',.3,'J','Wđ = W − Wt = 0,4 − 0,1 = 0,3 J.','Biến thể bảo toàn cơ năng','Tổng động năng và thế năng là cơ năng.');
export const questions=bank;
export const topics={basics:{name:'Giải mã dao động',icon:'φ',desc:'Nắm chắc đại lượng, phương trình và chuyển động. Gỡ những nhầm lẫn quen thuộc.',tag:'Trạm 01 · Nền tảng'},graphs:{name:'Chinh phục đồ thị',icon:'∿',desc:'Đọc tín hiệu, tìm chu kì và giải mã chuyển động từ những đường cong.',tag:'Trạm 02 · Quan sát'},energy:{name:'Lõi năng lượng',icon:'ϟ',desc:'Khôi phục nguồn năng lượng. Kết nối cơ năng, động năng và thế năng.',tag:'Trạm 03 · Vận dụng'},mixed:{name:'Thử thách tổng hợp',icon:'✧',desc:'Một hành trình 12 câu qua cả ba trạm. Tự kiểm tra trước ngày thi.',tag:'Nhiệm vụ cuối · 12 câu'}};
export function parseNumeric(raw){const s=String(raw).trim().replace(/−/g,'-').replace(',','.');return /^[+-]?(?:\d+(?:\.\d*)?|\.\d+)(?:e[+-]?\d+)?$/i.test(s)?Number(s):NaN;}
export function isCorrect(q,response){return q.type==='number'?Number.isFinite(parseNumeric(response))&&Math.abs(parseNumeric(response)-q.answer)<=q.tolerance:Number.isInteger(response)&&response===q.answer;}
