// 25 câu mã 1101 và 7 câu bổ trợ. Đáp án nguồn: dòng mã 1101, không dùng dòng 0000.
const bank=[];
function mc(id,topic,prompt,options,answer,explanation,source,hint,graph){bank.push({id,topic,type:'choice',prompt,options,answer,explanation,source,hint,graph});}
function num(id,topic,prompt,answer,unit,explanation,source,hint,graph,tolerance=.001){bank.push({id,topic,type:'number',prompt,answer,unit,explanation,source,hint,graph,tolerance});}
const compass={kind:'compass'};
const route={kind:'route'};
const carRoute={kind:'carRoute'};
const simple={kind:'motion',points:[[0,0],[1,2],[2,4],[3,6],[4,6],[5,6]],maxT:5,minD:0,maxD:7,stepT:1,stepD:2,table:true};
const complex={kind:'motion',points:[[0,0],[3,6],[5,6],[9,-2],[12,-2]],maxT:12,minD:-3,maxD:7,stepT:1,stepD:1};
const trip='Mẹ đưa Minh đến thư viện lúc 8 giờ. Sau 5 phút, xe đạt 24 km/h. Sau 10 phút nữa, tốc độ tăng thêm 12 km/h. Xe dừng tại thư viện lúc 8 giờ 25 phút. Quãng đường cả hành trình là 10 km.';
mc('10q01','displacement','Các vectơ xuất phát từ O; tỉ xích 1 cm ứng với 50 m. Vectơ d₄ có độ lớn và hướng nào?',['100 m, hướng Tây','100 m, hướng Đông','50 m, hướng Đông','200 m, hướng Tây'],0,'d₄ dài 2 cm trên hình: độ lớn bằng 2 × 50 = 100 m. Mũi tên chỉ về phía Tây.','1101 · Câu 1','Dùng số đo ghi trên hình, không đo kích thước màn hình.',compass);
mc('10q02','displacement','Với tỉ xích 1 cm ứng với 50 m, vectơ d₁ có độ lớn và hướng nào?',['50 m, hướng Nam','150 m, hướng Bắc','300 m, hướng Bắc','150 m, hướng Nam'],1,'d₁ dài 3 cm, hướng Bắc ⇒ độ lớn 3 × 50 = 150 m, hướng Bắc.','1101 · Câu 2','Đọc số đo và chiều của mũi tên d₁.',compass);
mc('10q03','displacement','Với tỉ xích 1 cm ứng với 50 m, vectơ d₂ có độ lớn và hướng nào?',['200 m, hướng Đông Nam','200 m, hướng Đông Bắc, hợp hướng Đông góc 45°','400 m, hướng Tây Bắc','100 m, hướng Đông Bắc'],1,'d₂ dài 4 cm ⇒ độ lớn 200 m. Mũi tên ở phía Đông Bắc, hợp hướng Đông góc 45°.','1101 · Câu 3','Xác định cả độ lớn, hướng và góc.',compass);
mc('10q04','displacement','Vật dịch chuyển từ O theo d₃. Với tỉ xích 1 cm ứng với 50 m, độ lớn và hướng là…',['100 m, hướng Đông','500 m, hướng Tây','250 m, hướng Tây','250 m, hướng Đông'],3,'d₃ dài 5 cm ⇒ 5 × 50 = 250 m. Mũi tên hướng Đông.','1101 · Câu 4','Độ lớn thực = số đo trên hình × tỉ xích.',compass);
mc('10q05','displacement','An đi từ siêu thị trở về nhà. Quãng đường và độ dịch chuyển lần lượt là bao nhiêu?',['1 800 m và 0 m','900 m và +900 m','900 m và −900 m','−900 m và −900 m'],2,'Quãng đường s = 900 m. Độ dịch chuyển d = x cuối − x đầu = 0 − 900 = −900 m. Quãng đường không âm.','1101 · Câu 5','Chiều dương từ nhà đến trường.',route);
mc('10q06','displacement','An đi từ nhà đến siêu thị rồi trở về nhà cất đồ. Quãng đường và độ dịch chuyển là…',['0 m và 0 m','1 800 m và 0 m','900 m và 0 m','1 800 m và +1 800 m'],1,'s = 900 + 900 = 1 800 m. Điểm cuối trùng điểm đầu nên d = 0.','1101 · Câu 6','Độ dịch chuyển chỉ phụ thuộc vị trí đầu và cuối.',route);
mc('10q07','displacement','An đi nhà → siêu thị → nhà → trường. Tổng quãng đường và độ dịch chuyển là…',['3 300 m và +1 500 m','3 300 m và 0 m','1 500 m và +1 500 m','2 400 m và +1 500 m'],0,'s = 900 + 900 + 1 500 = 3 300 m. d = 1 500 − 0 = +1 500 m.','1101 · Câu 7','Cộng độ dài từng chặng để tính s; lấy toạ độ cuối trừ đầu để tính d.',route);
mc('10q08','displacement','An đi từ trạm xăng đến siêu thị. Quãng đường và độ dịch chuyển là…',['600 m và −600 m','600 m và +600 m','1 200 m và +600 m','900 m và +900 m'],1,'s = 900 − 300 = 600 m. Xe đi theo chiều dương, d = +600 m.','1101 · Câu 8','Hai địa điểm có toạ độ 300 m và 900 m.',route);
mc('10q09','displacement','Ô tô đi 6 km về Tây, 4 km về Nam rồi 3 km về Đông. Độ lớn độ dịch chuyển của cả hành trình bằng bao nhiêu?',['3 km','13 km','5 km','7 km'],2,'Độ dịch chuyển tổng có thành phần 3 km về Tây và 4 km về Nam. Độ lớn = √(3² + 4²) = 5 km.','1101 · Câu 9','Hai thành phần vuông góc tạo thành tam giác vuông.',carRoute);
mc('10q10','displacement','Sau hành trình 6 km về Tây, 4 km về Nam, 3 km về Đông, vị trí cuối của ô tô so với điểm xuất phát là…',['Phía Tây 3 km và phía Bắc 4 km','Phía Tây 9 km và phía Nam 4 km','Phía Đông 3 km và phía Nam 4 km','Phía Tây 3 km và phía Nam 4 km'],3,'Theo Đông–Tây: −6 + 3 = −3 km, tức Tây 3 km. Theo Bắc–Nam: Nam 4 km.','1101 · Câu 10','Cộng các đoạn có cùng phương theo dấu.',carRoute);
mc('10q11','displacement','Vectơ độ dịch chuyển của hành trình 6 km về Tây, 4 km về Nam, 3 km về Đông hướng về phía nào?',['Đông Bắc','Tây Bắc','Tây Nam','Đông Nam'],2,'Điểm cuối nằm phía Tây và phía Nam so với điểm đầu, nên vectơ tổng hướng Tây Nam.','1101 · Câu 11','Nối thẳng điểm xuất phát với điểm kết thúc.',carRoute);
mc('10q12','displacement','Ô tô đi 6 km về Tây, 4 km về Nam rồi 3 km về Đông. Tổng quãng đường bằng bao nhiêu?',['9 km','13 km','10 km','5 km'],1,'Quãng đường là tổng độ dài các chặng: s = 6 + 4 + 3 = 13 km.','1101 · Câu 12','Quãng đường không triệt tiêu khi đổi hướng.',carRoute);
mc('10q13','speed',trip+' Thời gian đi từ nhà đến thư viện là bao nhiêu?',['15 phút','25 phút','20 phút','30 phút'],1,'Δt = 8 giờ 25 phút − 8 giờ = 25 phút. Không chỉ cộng 5 phút và 10 phút vì còn chặng cuối.','1101 · Câu 13','Lấy thời điểm kết thúc trừ thời điểm bắt đầu.');
mc('10q14','speed',trip+' Tốc độ lúc 8 giờ 25 phút bằng bao nhiêu và thuộc loại nào?',['24 km/h, tốc độ tức thời','24 km/h, tốc độ trung bình cả hành trình','0 km/h, tốc độ trung bình cả hành trình','0 km/h, tốc độ tức thời'],3,'Lúc 8 giờ 25 phút xe đã dừng nên tốc độ tức thời bằng 0. Tốc độ trung bình cả hành trình vẫn khác 0.','1101 · Câu 14','Một giá trị tại một thời điểm là tốc độ tức thời.');
mc('10q15','speed',trip+' Tốc độ lúc 8 giờ 15 phút bằng bao nhiêu và thuộc loại nào?',['24 km/h, tốc độ trung bình','36 km/h, tốc độ trung bình','36 km/h, tốc độ tức thời','12 km/h, tốc độ tức thời'],2,'8 giờ 15 phút là sau 5 + 10 phút. Tốc độ lúc đó = 24 + 12 = 36 km/h, là tốc độ tức thời.','1101 · Câu 15','“Tăng thêm 12” không có nghĩa là tốc độ mới bằng 12.');
mc('10q16','speed',trip+' Tốc độ trung bình cả hành trình là…',['24 km/h','36 km/h','30 km/h','40 km/h'],0,'Thời gian 25 phút = 25/60 giờ. Tốc độ trung bình = 10 ÷ (25/60) = 24 km/h. Không lấy trung bình cộng các tốc độ tức thời.','1101 · Câu 16','Tốc độ trung bình = tổng quãng đường / tổng thời gian.');
num('10s01','speed','Một bạn đi 900 m rồi quay về điểm xuất phát, hết tổng cộng 600 s. Tốc độ trung bình bằng bao nhiêu?',3,'m/s','Tổng quãng đường = 1 800 m. Tốc độ trung bình = 1 800/600 = 3 m/s.','Bổ trợ 1101 · Câu 6, 16','Đừng dùng độ dịch chuyển thay cho quãng đường.');
num('10s02','speed','Một bạn đi 900 m rồi quay về điểm xuất phát, hết tổng cộng 600 s. Vận tốc trung bình trên đường thẳng bằng bao nhiêu?',0,'m/s','Độ dịch chuyển bằng 0 nên vận tốc trung bình = 0/600 = 0 m/s.','Bổ trợ 1101 · Câu 6, 18','Vận tốc trung bình = độ dịch chuyển / thời gian.');
num('10s03','speed','Đổi tốc độ 36 km/h sang m/s.',10,'m/s','36 km/h = 36 × 1 000/3 600 = 10 m/s.','Bổ trợ kỹ năng đổi đơn vị tốc độ','Chia số đo km/h cho 3,6.');
num('10s04','speed','Vật chuyển động thẳng từ x = 9 m đến x = 3 m trong 2 s. Vận tốc trung bình bằng bao nhiêu?',-3,'m/s','d = 3 − 9 = −6 m. Vận tốc trung bình = −6/2 = −3 m/s; dấu âm chỉ chiều chuyển động.','Bổ trợ 1101 · Câu 22','Lấy toạ độ cuối trừ toạ độ đầu.');
mc('10q17','graphs','Bảng dưới ghi độ dịch chuyển của xe đồ chơi. Trong 3 giây đầu, xe chuyển động như thế nào?',['Đứng yên','Thẳng đều theo chiều dương','Nhanh dần','Chậm dần'],1,'Mỗi giây độ dịch chuyển tăng 2 m, nên vận tốc không đổi bằng +2 m/s.','1101 · Câu 17','So sánh độ tăng d trong những khoảng thời gian bằng nhau.',simple);
mc('10q18','graphs','Vận tốc trung bình của xe trong toàn bộ 5 giây bằng bao nhiêu?',['1,2 m/s','3 m/s','0 m/s','2 m/s'],0,'v trung bình = (6 − 0)/(5 − 0) = 1,2 m/s, kể cả khoảng đứng yên.','1101 · Câu 18','Dùng toàn bộ 5 giây, không chỉ 3 giây chuyển động.',simple);
mc('10q19','graphs','Xe có bảng t (s): 0; 1; 2; 3; 4; 5 và d (m): 0; 2; 4; 6; 6; 6. Đồ thị nào mô tả đúng?',['Hình I','Hình III','Hình II','Hình IV'],2,'Hình II đi từ (0;0) đến (3;6), sau đó nằm ngang đến (5;6), đúng với bảng. Hình I đi đều suốt; III quay về; IV đứng yên từ đầu.','1101 · Câu 19','Đồ thị phải tăng đều đến 3 s rồi nằm ngang.',{kind:'motionChoices'});
mc('10q20','graphs','Từ 3 s đến 5 s, xe đồ chơi ở trạng thái nào?',['Thẳng đều với vận tốc 6 m/s','Chậm dần rồi dừng lại','Đứng yên tại vị trí cách vị trí đầu 6 m','Chuyển động ngược chiều dương'],2,'Độ dịch chuyển giữ nguyên 6 m trong khoảng này, nên xe đứng yên. 6 m là vị trí, không phải vận tốc.','1101 · Câu 20','Đoạn nằm ngang trên đồ thị d–t có độ dốc bằng 0.',simple);
mc('10q21','graphs','Vận tốc của xe trong 3 giây đầu bằng bao nhiêu?',['6 m/s','3 m/s','2 m/s','1,2 m/s'],2,'v = Δd/Δt = (6 − 0)/(3 − 0) = 2 m/s.','1101 · Câu 21','Vận tốc bằng độ dốc đồ thị d–t.',simple);
mc('10q22','graphs','Từ 5 s đến 9 s, tốc độ và vận tốc của xe lần lượt là…',['2 m/s và −2 m/s','1,5 m/s và −1,5 m/s','−2 m/s và −2 m/s','2 m/s và +2 m/s'],0,'v = (−2 − 6)/(9 − 5) = −2 m/s. Xe chuyển động đều theo chiều âm; tốc độ là |v| = 2 m/s.','1101 · Câu 22','Dùng hiệu toạ độ và hiệu thời gian của đoạn đi xuống.',complex);
mc('10q23','graphs','Toạ độ của xe tại 2 s, 4 s, 8 s và 12 s lần lượt là…',['4 m; 6 m; 2 m; −2 m','2 m; 6 m; 0 m; −2 m','4 m; 6 m; 0 m; 2 m','4 m; 6 m; 0 m; −2 m'],3,'Đọc trên từng đoạn: x(2) = 4 m; x(4) = 6 m; x(8) = 0; x(12) = −2 m. Gốc toạ độ là điểm xuất phát nên x = d.','1101 · Câu 23','Dóng từng thời điểm lên đường biểu diễn.',complex);
mc('10q24','graphs','Sau 12 s, quãng đường và độ dịch chuyển của xe lần lượt là…',['14 m và −2 m','6 m và 0 m','8 m và −2 m','14 m và 2 m'],0,'s = |6 − 0| + |−2 − 6| = 6 + 8 = 14 m. d = −2 − 0 = −2 m. Hai đoạn đứng yên không tăng quãng đường.','1101 · Câu 24','Cộng độ dài di chuyển từng đoạn, không cộng thời gian đứng yên.',complex);
mc('10q25','graphs','Mô tả nào đúng với toàn bộ chuyển động của xe?',['Theo chiều dương, dừng lại, theo chiều âm rồi dừng lại','Theo chiều dương rồi đứng yên từ 3 s đến 12 s','Liên tục theo chiều dương trong 12 s','Theo chiều âm, dừng lại rồi theo chiều dương'],0,'0–3 s: d tăng; 3–5 s: d không đổi; 5–9 s: d giảm; 9–12 s: d không đổi. Tương ứng đi dương → đứng yên → đi âm → đứng yên.','1101 · Câu 25','Xét dấu độ dốc từng đoạn, không xét riêng dấu toạ độ.',complex);
num('10g01','graphs','Dựa vào đồ thị, tổng thời gian xe đứng yên trong 12 s là bao nhiêu?',5,'s','Đứng yên từ 3 đến 5 s (2 s) và từ 9 đến 12 s (3 s): tổng 5 s.','Bổ trợ 1101 · Câu 25','Tìm hai đoạn nằm ngang.',complex);
num('10g02','graphs','Dựa vào đồ thị, vận tốc của xe trong khoảng 5–9 s bằng bao nhiêu?',-2,'m/s','v = (−2 − 6)/(9 − 5) = −8/4 = −2 m/s.','Bổ trợ 1101 · Câu 22','Nhập cả dấu âm nếu vật đi theo chiều âm.',complex);
num('10g03','graphs','Tốc độ trung bình trong toàn bộ 12 s bằng bao nhiêu? Làm tròn đến hàng phần trăm.',1.17,'m/s','Quãng đường 14 m, thời gian 12 s ⇒ tốc độ trung bình = 14/12 ≈ 1,17 m/s.','Bổ trợ 1101 · Câu 24','Cộng quãng đường rồi chia cho 12 s.',complex,.0001);
for(const q of bank.filter(q=>['10q13','10q14','10q15','10q16'].includes(q.id))){q.context=trip;q.prompt=q.prompt.slice(trip.length).trim();}
export const questions10=bank;
export const topics10={displacement:{name:'La bàn dịch chuyển',icon:'↗',desc:'Đọc vectơ, xác định phương hướng. Phân biệt đường đã đi và vị trí cuối.',tag:'Trạm 01 · Khám phá'},speed:{name:'Chặng đua tốc độ',icon:'◷',desc:'Giải mã thời gian, tốc độ tức thời và trung bình. Chú ý dấu và đơn vị.',tag:'Trạm 02 · Tính toán'},graphs:{name:'Thám tử chuyển động',icon:'⌁',desc:'Từ bảng và đồ thị d–t, tìm vận tốc, đoạn đứng yên và hành trình của xe.',tag:'Trạm 03 · Quan sát'},mixed:{name:'Thử thách tổng hợp',icon:'✧',desc:'12 câu qua cả ba trạm. Kết nối vectơ, tốc độ và đồ thị trước bài kiểm tra.',tag:'Nhiệm vụ cuối · 12 câu'}};
